#logging.file=pretty.log
#logging.level.com.shop=debug
#logging.level.org.springframework=info
#server.port: 8080
#spring:
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: products